# Generated by Django 3.1.7 on 2021-03-31 14:16

from django.db import migrations, models
import service.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urunresimler',
            name='urunresim',
            field=models.ImageField(default='', editable=False, upload_to=service.models.file_urun_save, verbose_name='Ürün Resim '),
        ),
    ]
