# Generated by Django 3.1.7 on 2021-03-31 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0002_urunresimler_urunresim'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdresModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('adres', models.CharField(max_length=255, verbose_name='Adres')),
                ('yedekTelefon', models.CharField(max_length=255, verbose_name='Telefon')),
                ('ilce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.ilcemodel', verbose_name='Ilce')),
                ('sehir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.sehirmodel', verbose_name='Şehir')),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adres',
                'verbose_name_plural': 'Adres',
                'db_table': 'adrestb',
                'ordering': ['-create_at'],
            },
        ),
        migrations.RemoveField(
            model_name='kampanyamodel',
            name='userid',
        ),
        migrations.DeleteModel(
            name='KampanayaUrun',
        ),
        migrations.DeleteModel(
            name='KampanyaModel',
        ),
    ]
