# Generated by Django 3.1.7 on 2021-05-20 15:52

from django.db import migrations, models
import service.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210520_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urunresimler',
            name='urunresim',
            field=models.ImageField(upload_to=service.models.file_urun_save, verbose_name='Ürün Resim '),
        ),
    ]
