# Generated by Django 3.1.7 on 2021-05-20 18:04

from django.db import migrations, models
import service.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20210520_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='urunmodel',
            name='resim',
            field=models.ImageField(default=False, upload_to=service.models.file_urun_save, verbose_name='Ürün Resim '),
        ),
    ]
