# Generated by Django 3.1.7 on 2021-03-31 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20210331_2032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KargoModel',
        ),
    ]
