# Generated by Django 3.1.7 on 2021-05-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20210504_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='urunresimler',
            name='sliderresim',
            field=models.BooleanField(default=False, verbose_name='Sliderde Gösterilsin Mi '),
        ),
    ]
