# Generated by Django 3.1.7 on 2021-05-20 18:08

from django.db import migrations, models
import service.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_urunmodel_resim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urunmodel',
            name='resim',
            field=models.ImageField(default=False, upload_to=service.models.file_resim_save, verbose_name='Ürün Resim '),
        ),
    ]
