# Generated by Django 3.1.7 on 2021-04-02 07:11

from django.db import migrations, models
import service.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_delete_kargomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategorimodel',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=255, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='urunmodel',
            name='slug',
            field=models.SlugField(default='', editable=False, verbose_name='Ürün Slug'),
        ),
        migrations.AlterField(
            model_name='urunresimler',
            name='urunresim',
            field=models.ImageField(upload_to=service.models.file_urun_save, verbose_name='Ürün Resim '),
        ),
    ]
