# Generated by Django 3.1.7 on 2021-04-05 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20210402_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urunmodel',
            name='altkategoriId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.altkategorimodel', verbose_name='Alt Kategori'),
        ),
    ]
