# Generated by Django 3.1.7 on 2021-05-20 18:47

from django.db import migrations, models
import service.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20210520_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urunmodel',
            name='resim',
            field=models.ImageField(blank=True, upload_to=service.models.upload_to, verbose_name='Ürün Resim '),
        ),
    ]
