# Generated by Django 3.1.7 on 2021-05-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20210520_2147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urunmodel',
            options={'ordering': ['-create_at'], 'verbose_name': 'Ürün Ekleme', 'verbose_name_plural': 'Ürün Ekleme'},
        ),
        migrations.AddField(
            model_name='urunmodel',
            name='sliderresim',
            field=models.BooleanField(default=False, verbose_name='Sliderde Gösterilsin Mi '),
        ),
    ]
