# Generated by Django 3.1.7 on 2021-03-30 18:24

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usermodel',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='usermodel',
            name='dogumtarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi '),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='profil',
            field=models.ImageField(default='profil', upload_to=authentication.models.file_profil_save, verbose_name='Kullanıcı Fotoğrafı'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='is_superuser',
            field=models.BooleanField(default=True, verbose_name='Super User'),
        ),
    ]
